# Generated by Django 3.0.6 on 2020-05-24 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='adhar',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='age',
            field=models.IntegerField(),
        ),
    ]
