# Generated by Django 3.0.6 on 2020-06-04 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_app', '0004_route_distance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='station_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket_app.Station'),
        ),
        migrations.AlterField(
            model_name='route',
            name='train_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket_app.Train'),
        ),
        migrations.AlterField(
            model_name='train',
            name='source_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket_app.Station'),
        ),
    ]
