# Generated by Django 3.0.6 on 2020-06-04 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_app', '0005_auto_20200604_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='train',
            name='destination_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination', to='ticket_app.Station'),
        ),
        migrations.AlterField(
            model_name='train',
            name='source_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source', to='ticket_app.Station'),
        ),
    ]
