# Generated by Django 3.0.8 on 2020-07-29 12:45

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_app', '0006_auto_20200604_1436'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('Name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Email', models.EmailField(max_length=254)),
                ('Phone_no', phone_field.models.PhoneField(max_length=31)),
            ],
        ),
        migrations.RemoveField(
            model_name='route',
            name='station_id',
        ),
        migrations.RemoveField(
            model_name='route',
            name='train_id',
        ),
        migrations.RemoveField(
            model_name='train',
            name='destination_id',
        ),
        migrations.RemoveField(
            model_name='train',
            name='source_id',
        ),
        migrations.DeleteModel(
            name='User_info',
        ),
        migrations.DeleteModel(
            name='Route',
        ),
        migrations.DeleteModel(
            name='Station',
        ),
        migrations.DeleteModel(
            name='Train',
        ),
    ]
