# Generated by Django 3.0.8 on 2020-07-29 18:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_app', '0007_auto_20200729_1815'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customers',
            name='Phone_no',
        ),
        migrations.AddField(
            model_name='customers',
            name='phone_number',
            field=models.CharField(blank=True, max_length=12, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
